"""create db

Revision ID: 8a14a3b6e2ac
Revises: 
Create Date: 2019-10-21 15:44:30.642881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a14a3b6e2ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('short_name', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.BigInteger(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('creator_id_user', sa.Integer(), nullable=True),
    sa.Column('creation_time', sa.DateTime(), nullable=True),
    sa.Column('modification_time', sa.DateTime(), nullable=True),
    sa.Column('is_actual', sa.Boolean(), nullable=True),
    sa.Column('id_default_currency', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id_user'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_default_currency'], ['currency.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('telegram')
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_currency', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('creation_time', sa.String(), nullable=True),
    sa.Column('modification_time', sa.String(), nullable=True),
    sa.Column('is_actual', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_currency'], ['currency.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('creation_time', sa.String(), nullable=True),
    sa.Column('modification_time', sa.String(), nullable=True),
    sa.Column('is_actual', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shared_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id_user', sa.Integer(), nullable=True),
    sa.Column('id_currency', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('decscription', sa.String(), nullable=True),
    sa.Column('creation_time', sa.String(), nullable=True),
    sa.Column('modification_time', sa.String(), nullable=True),
    sa.Column('is_actual', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_currency'], ['currency.id'], ),
    sa.ForeignKeyConstraint(['owner_id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('creation_time', sa.String(), nullable=True),
    sa.Column('modification_time', sa.String(), nullable=True),
    sa.Column('is_actual', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('currency_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_account', sa.Integer(), nullable=True),
    sa.Column('id_account_currency', sa.Integer(), nullable=True),
    sa.Column('id_default_currency', sa.Integer(), nullable=True),
    sa.Column('rate', sa.Numeric(), nullable=True),
    sa.Column('operation_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_account'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('future_operation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cat', sa.Integer(), nullable=True),
    sa.Column('id_account', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('decscription', sa.String(), nullable=True),
    sa.Column('creation_time', sa.String(), nullable=True),
    sa.Column('modification_time', sa.String(), nullable=True),
    sa.Column('is_actual', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_account'], ['account.id'], ),
    sa.ForeignKeyConstraint(['id_cat'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shared_acc_user',
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_shared_acc', sa.Integer(), nullable=True),
    sa.Column('user_ratio', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_shared_acc'], ['shared_account.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], )
    )
    op.create_table('shared_operation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_shared_acc', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('decscription', sa.String(), nullable=True),
    sa.Column('creation_time', sa.String(), nullable=True),
    sa.Column('modification_time', sa.String(), nullable=True),
    sa.Column('is_actual', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_shared_acc'], ['shared_account.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cat', sa.Integer(), nullable=True),
    sa.Column('id_account', sa.Integer(), nullable=True),
    sa.Column('id_shared_operation', sa.Integer(), nullable=True),
    sa.Column('id_future_operation', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.Column('creation_type', sa.String(), nullable=True),
    sa.Column('creator_id_user', sa.Integer(), nullable=True),
    sa.Column('creation_time', sa.DateTime(), nullable=True),
    sa.Column('modification_time', sa.DateTime(), nullable=True),
    sa.Column('is_actual', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id_user'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_account'], ['account.id'], ),
    sa.ForeignKeyConstraint(['id_cat'], ['category.id'], ),
    sa.ForeignKeyConstraint(['id_future_operation'], ['future_operation.id'], ),
    sa.ForeignKeyConstraint(['id_shared_operation'], ['shared_operation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation_tag',
    sa.Column('id_tag', sa.Integer(), nullable=False),
    sa.Column('id_operation', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_operation'], ['operation.id'], ),
    sa.ForeignKeyConstraint(['id_tag'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('id_tag', 'id_operation')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation_tag')
    op.drop_table('operation')
    op.drop_table('shared_operation')
    op.drop_table('shared_acc_user')
    op.drop_table('future_operation')
    op.drop_table('currency_rate')
    op.drop_table('tag')
    op.drop_table('shared_account')
    op.drop_table('category')
    op.drop_table('account')
    op.drop_table('user')
    op.drop_table('currency')
    # ### end Alembic commands ###
